# Generated by Django 4.2.3 on 2023-07-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_colorvariant_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizevariant',
            old_name='Color',
            new_name='Color_id',
        ),
    ]
