# Generated by Django 4.2.3 on 2023-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_color_sizevariant_color_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
