# Generated by Django 4.2.3 on 2023-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sizevariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
