# Generated by Django 4.2.3 on 2023-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sizevariant_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
    ]
