# Generated by Django 4.2.3 on 2023-07-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='Color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.colorvariant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='product_id',
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
            preserve_default=False,
        ),
    ]
