# Generated by Django 4.2.3 on 2023-07-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_sizevariant_color_id_remove_colorvariant_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
            preserve_default=False,
        ),
    ]
