# Generated by Django 4.2.3 on 2023-07-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_sizevariant_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='Color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.colorvariant'),
            preserve_default=False,
        ),
    ]
