# Generated by Django 4.2.3 on 2023-07-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ucart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='product_varient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.sizevariant'),
            preserve_default=False,
        ),
    ]
