# Generated by Django 4.2.3 on 2023-07-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_cart_items_product_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='product_varient',
            field=models.ForeignKey(default='471d64a9-47bb-4015-9ebc-259aff491edf', on_delete=django.db.models.deletion.CASCADE, to='store.sizevariant'),
            preserve_default=False,
        ),
    ]
