# Generated by Django 4.2.3 on 2023-07-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_items_product_varient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_items',
            old_name='product_varient',
            new_name='product_variant',
        ),
    ]
