# Generated by Django 4.2.3 on 2023-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_product_varient_cart_items_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='product_variant',
            field=models.CharField(max_length=50),
        ),
    ]
