# Generated by Django 4.2.3 on 2023-07-22 04:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0025_order_pincode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_Items',
            new_name='CartItems',
        ),
    ]
