# Generated by Django 4.2.3 on 2023-07-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_cart_items_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('MinPurchase', models.FloatField()),
                ('ExpDate', models.DateField()),
                ('amount', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
