# Generated by Django 4.2.3 on 2023-07-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
