# Generated by Django 4.2.3 on 2023-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(max_length=50),
        ),
    ]
