# Generated by Django 4.2.3 on 2023-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
