# Generated by Django 4.2.3 on 2023-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_guest_wishlist_date_added_wishlist_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date_added',
        ),
    ]
