# Generated by Django 4.2.3 on 2023-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_wishlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_id',
            field=models.CharField(max_length=255),
        ),
    ]
