# Generated by Django 4.2.3 on 2023-07-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_guest_wishlist_date_added_wishlist_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
