# Generated by Django 4.2.3 on 2023-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_coupons_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
