# Generated by Django 4.2.3 on 2023-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_return_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
