# Generated by Django 4.2.3 on 2023-08-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_orderproduct_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_request',
            name='variant_id',
        ),
    ]
