# Generated by Django 4.2.3 on 2023-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='rprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
